[env]
TERM = "xterm-256color"

[window]
decorations = "none"
startup_mode = "maximized"
dynamic_title = true
dynamic_padding = true
opacity = 0.85

[font]
size = 16

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args= ["-l", "-c", "tmux attach || tmux"]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

[cursor]
style.shape="Beam"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/github_dark_high_contrast.toml",
]

