import = [
    "~/.config/alacritty/themes/github_dark_high_contrast.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
startup_mode = "maximized"
dynamic_title = true
opacity = 0.7
dynamic_padding = true

[font]
size = 16

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[shell]
program = "/bin/zsh"
args= ["-l", "-c", "tmux attach || tmux"]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
